### PR TITLE
Lazy load

### PR DESCRIPTION
**Pull request by tomitrescak**
Can you please review if this is the way you envisioned to do lazy loads?
If so, please merge ;)

Also, please please think of me with that Typescript enhancement, it';s the only way blocking me with adoption of Fusebox which I already love from the bottom of my heart ;)

### CODE REVIEW

**Comment by nchanged** [comment]
@tomitrescak Good job! I will check in a bit!

**Comment by tomitrescak** [comment]
Hmm, while this partially does the job, it does not do what I would expect.
What I imagine is a code-split like in webpack, where also splitted files are dynamically updated. 

Also, splits create a lot of redundancy if I am for example splitting files by routes inmy application. All shared code will be redundantly placed in all bundles.

Hot reload does not work on these split bundles as well ;(

**Comment by nchanged** [comment]
Yeah i know. This should be improved. 
> shared code will be redundantly placed in all bundles.

Can you isolate dependencies? As FuseBox understands shared bundles? Like `[lib/helper.ts]` or `-something`

**Comment by nchanged** [comment]
Awesomeness is coming! 
https://github.com/fuse-box/fuse-box/pull/158

We will introduce a custom HMR for react.

**Comment by tomitrescak** [comment]
How would I isolate dependencies in my own package? I can isolate those from node_modules, but my app code will be spread across several bundles.

**Comment by nchanged** [comment]
by using arithmetics
```
fuse.bundle({
  "main.js" :  `> index.ts -components/**/**.ts - lib/**/**.ts`,
  "components.js" :  `+ [components/**/**.ts]`,
  "lib.js" :  `+ [lib/**/**.ts]`,

  "vendor.js" :  `+ react + react-dom`
})

```

**Comment by nchanged** [comment]
It is working like you wanted =)
https://github.com/fuse-box/fuse-box-ts-react-reflux-seed/blob/master/src/client/components/HelloWorld.tsx#L26

lazy.ts was in project, i removed it from there, to actually test it

**Pull request merged**
