### PR TITLE
Automatic hashing and bundle split in production

### PR DESCRIPTION
**Pull request by tomitrescak**
Modified gulp so that it adds automatically content hashes to generated bundles in index.html file.
<script src="app.js" />
becomes
<script src="app.js?chp=#hash />

Hash is generated by file contents.
This is very useful for production builds.

Also, vendor bundle is generated into production dir as well.

### CODE REVIEW

**Comment by tomitrescak** [comment]
I have also added the possibility to serve both production and development versions. If development exists it is server

~~**BUT**~~

~~**THE PRODUCTION VERSION DOES NOT WORK!".~~
~~By now I have not been able to produce a production build that would work in the browser.~~
~~When production bundles are served .. nothing happens.~~

[EDIT]

I have modified the starting point of the production bundle which now correctly launches in the browser.

**Comment by nchanged** [comment]
Thanks!!!

**Comment by nchanged** [comment]
One thing tho, I did not get why bundle.js and app.ts both have vendors? And the same size? You think you can fix that? thanks!

**Comment by tomitrescak** [comment]
I'm not sure what you mean.

One vendor.js (non-minified) is in development build
Other vendor.js (minified) is in production build.

**Comment by nchanged** [comment]
index.html requires 2 files. app.js and bundle.js which are the same size..

**Comment by tomitrescak** [comment]
I renamed bundle.js to app.js. I'm pretty sure it's a zombie file. There is no bundle.js in whole project ... maybe you just need to delete your existing directories and have gulp re-generate the dirs for you.

**Comment by nchanged** [comment]
Ok! Great!

**Comment by tomitrescak** [comment]
I will add a lazy loading example here as well and you'll need to review whether it's good or not.

**Comment by nchanged** [comment]
That would be cool! Thanks!

**Pull request merged**
