### PR TITLE
move `hmr` code to not depend on application code in any way :rose:

### PR DESCRIPTION
**Pull request by basarat**
/cc @tomitrescak so you can copy `hmr.ts` to any code base you want to try :heart:

### CODE REVIEW

**Comment by tomitrescak** [comment]
Hmm, I just do not know how to make it work. Copying the hmr to my project and then setting:

```
import { setStatefulModules } from './hmr';
setStatefulModules('hmr', 'luis/', 'components/');
```

ALWAYS leads to full page reload ;(

'luis' is a name of the folder where I have components which I want to hot reload
'components` .. well thats just to test if I needed this.

**Comment by basarat** [comment]
@tomitrescak example with yester coming. Working on integrating into fuse-box so you don't need to copy files :rose: https://github.com/fuse-box/fuse-box/pull/232

**Comment by basarat** [comment]
> ALWAYS leads to full page reload ;(

you can put a console.log here : https://github.com/fuse-box/fuse-box-ts-react-reflux-seed/pull/7/files#diff-25a3b027a589387051e401b9733bf2faR8 to see why its considered a stateful module. Suspect `components/` is wrong :rose:

**Comment by tomitrescak** [comment]
Ok, so the list means path that I DO NOT want hot reload.
I did `setStatefulModules('hmr');`

now it hot reloads, but it does not maintain state in my opinion as page is re rendered. But maybe because I'm using only stateless components.

**Comment by nchanged** [comment]
@basarat that is confusing indeed ;-) Could you add it to the docs?

**Comment by basarat** [comment]
> so the list means path that I DO NOT want hot reload.

Yes. Stateful modules are the ones you don't want to patch. `setStatefulModules('modules that hold state and should not be flushed')`. Think its clear but I can see the confusion. 

That said just pushed `fuse-hmr` demo to yester : https://github.com/basarat/yester/commit/f78c00341d76d9338aed0b930d5de614899fbc32 

Note: you will not need `fuse-hmr` package once this https://github.com/fuse-box/fuse-box/pull/232 is merged :rose:

**Comment by basarat** [comment]
> I did setStatefulModules('hmr'); now it hot reloads, but it does not maintain state in my opinion as page is re rendered

Of course. Cause you just said only the `hmr` file is stateful. You need to add other files that hold state in there.

**Comment by basarat** [comment]
PS the new signature is better : a function so you get to use a regex or includes or whatever you want : https://github.com/fuse-box/fuse-box/pull/232/commits/6bc91cb635bee2d49ef2d3f082084b00bcb840c6#diff-1fb15e14062bc4d43a27219df7be4ef4R42 :rose:

**Comment by basarat** [comment]
@tomitrescak did you get it working? There are more docs here : https://github.com/basarat/fuse-hmr#setstatefulmodulesfusebox-modulenamesstring feeling the pain of trying to explain better 😢

**Comment by tomitrescak** [comment]
@basarat, I think so ;) With stateless components it's a bit tricky. But it seems that all is peachy now! :rose: Thanks!

Check out my next soon to be OSS that uses FuseBox. It's a StoryBook / Jest TestRunner hybrid that allows to view React components and to live display test results in browser and manipulate snapshots. The name is LUIS as *L*ist of *UIS* ;)

luis

There is a small bug in the video, where the snapshot compare after hot code reload does not load the server version correctly (it's empty) and I have to do full window reload, but it's going to be solved.

what makes me drool is the speed ... fusebox is mind blowing. On original storybook I was getting tops 4-5 seconds reload but completely without sourcemaps. Sourcemapped reloads were taking more ten 8 seconds. Here it is instantaneous. I have about 200 components in my StoryBook.

**Comment by basarat** [comment]
@tomitrescak the next version of fusebox `x.x.119` will ship with this HMR support out of the box. Here is a blog post that I have lined up https://medium.com/@basarat/rethinking-hot-module-reloading-58ce15b5f496 :rose:

**Comment by jrmyio** [comment]
@tomitrescak would love to beta test

**Pull request merged**
